services:
  angular-app:
    build: .
    container_name: adoption-animal-app
    restart: unless-stopped
    ports:
      - "4200:80"    # HTTP -> redireciona para HTTPS
      - "4443:443"   # HTTPS
    networks:
      - controlimage_network

networks:
  controlimage_network:
    external: true
