services:
  angular-app:
    build: .
    container_name: adoption-animal-app
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP -> redireciona para HTTPS
      - "443:443"   # HTTPS padr√£o SEM PORTA
    networks:
      - controlimage_network

networks:
  controlimage_network:
    external: true
